server:
  port: 1001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  prefix: /api
  routes:
    services:
      path: /services/**
      service-id: SERVICE-A
    service:
      path: /services/**
      service-id: SERVICE-B  
spring:
    application:
     name: zuul-server
